# Dependencies
markdown:         kramdown
redcarpet:
  extensions:     [strikethrough,smart,with_toc_data]
highlighter:      rouge

# Permalinks
permalink:        /posts/:title/

# User Configuration
title:            feedrdr.blog
tagline:          'An open source RSS news reader to help you track and manage all the content you care about, getting better every week and made with ♥ in NYC'
description:      'Passionate about technology and building things'
url:              https://feedrdr.co/blog
baseurl:          '/'
paginate:         3
excerpt_separator: '<br>'
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

# Author Info
author:
  name:           'steven'
  url:            https://feedrdr.co/blog

# Social Integration
social:
  twitter:        steven
  disqus:         steven
  addthis_pubid:  

# Google Analytics Configuration
# Proxy response must be in JSON and should have the fields - ga:pagePath, ga:pageview
google_analytics:
  tracking_id:      
  super_proxy_url:  

# Github
github:
  repo:           https://github.com/feedrdr/web.blog.git
  feedback:       

# Version Info
version:          0.0.0
